src/objects/Puppy__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Picture_Path__c</fullName>
        <defaultValue>&apos;/servlet/servlet.FileDownload?file=015j00000005HzO&apos;</defaultValue>
        <label>Picture Path</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Puppy_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Puppy Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Puppies</relationshipLabel>
        <relationshipName>Puppies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Puppy</label>
    <nameField>
        <label>Puppy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puppies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Puppy_Location__c.object
<CustomObject>
    <label>Puppy Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puppy Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Puppy_Reservation__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Puppy_Location__c</fullName>
        <label>Puppy Location</label>
        <referenceTo>Puppy_Location__c</referenceTo>
        <relationshipLabel>Puppies</relationshipLabel>
        <relationshipName>Puppy</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Puppy__c</fullName>
        <label>Puppy</label>
        <referenceTo>Puppy__c</referenceTo>
        <relationshipLabel>Location</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Puppy Reservation</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Puppy Reservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Puppy Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TodayReservationsController.cls
public class TodayReservationsController {

    private Map<String,List<Puppy__c>> locationPuppyMap = new  Map<String,List<Puppy__c>>();  
    
    public TodayReservationsController(){
        
    	List<Puppy_Reservation__c> resList = [Select Puppy_Location__r.Name, Puppy__r.Name ,Puppy__r.Puppy_Owner__c, Puppy__r.Picture_Path__c, Puppy__r.Date_of_Birth__c, Date__c  from Puppy_Reservation__c where Date__c = TODAY];  
        for(Puppy_Reservation__c r : resList){
            Puppy__c puppy = new Puppy__c(Name=r.Puppy__r.Name, Picture_Path__c =r.Puppy__r.Picture_Path__c);
            if(locationPuppyMap.containsKey(r.Puppy_Location__r.Name)){
                locationPuppyMap.get(r.Puppy_Location__r.Name).add(puppy);
            }else{
                List<Puppy__c> puppyList = new List<Puppy__c>();
                puppyList.add(puppy);
                locationPuppyMap.put(r.Puppy_Location__r.Name,puppyList);
            }
        }
    }
    
    public Map<String,List<Puppy__c>> getLocationPuppyMap(){
        return locationPuppyMap;
    }
        
}